spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mapping
    username: mapping
    password: mapping
    platform: postgres
  jpa:
    hibernate:
      physical-naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicity-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false


# liquibase
url: jdbc:postgresql://localhost:5432/mapping
username: mapping
password: mapping
driver: org.postgresql.Driver
referenceUrl: hibernate:spring:br.com.welisson.jpamapping.domain?dialect=org.hibernate.dialect.PostgreSQLDialect
#changeLogFile: src/main/resources/db/changelog/changelog-master.yaml
outputChangeLogFile: src/main/resources/db/changelog/changelog-master.yaml
diffChangeLogFile: src/main/resources/db/changelog/liquibase-diff-changeLog.yaml